name: As long as I breathe
favicon: null
layout_spectrum: 0.14826246607117355
typography_spectrum: 0.29599163751117885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7403155711945146
  lightness: 0.8827855247072875
  saturation: 0.7628087110351771
  rhythmicContrast: 0.5651572498027235
purpose: []
